# Mod
modId=obs_overlay
modName=OBS Overlay
modDescription=Hide HUD elements from OBS stream by making them an overlay.
modAuthor=zziger
modVersion=2.0.0-fabric
modLicense=MIT
modSourcesURL=https://github.com/zziger/obs-overlay
modIssuesURL=https://github.com/zziger/obs-overlay/issues

# Dependencies
minecraftVersion=26.1.2
fabricVersion=0.19.3
loomVersion=1.16-SNAPSHOT
mixinVersion=0.12.5+mixin.0.8.5
clothConfigVersion=26.1.154
modmenuVersion=18.0.0-alpha.8
immediatelyfastVersion=1.8.1+26.1.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false